export const udyamitaTheme = {
  themeColor: '#DE5D83',
   primaryColor: '#028454',
  //primaryColor: '#FEC251',
  themeBgColor: '#FAFAFA',
  beeAppColor: '#028454',
  beeMitraAppColor:"#E56869",
  beeMitraquickLinkBgColor:'#F6DDDD',
  beeMitraDisabledButtonColor:'#EFB1B1',

  beeAppDisabledColor: '#7EBFA7',
  disabledButtonColor: 'rgba(2, 132, 84, 0.3)',
  beeAppBackGroundColor: '#EFEEEE',
  borderStyleColor: '#CBCBCB',
  quickLinkBgColor: '#C2EBDC',
  beeAppPrimaryBgColor: '#E6F3EE',
  borderStyleColor2: 'dimgrey',
  textColor: '#262626',
  mainThemeFontFamily: 'OpenSans-Regular',
  mainThemeFontFamilySemiBold: 'OpenSans-SemiBold',
  mainThemeFontFamilyMedium: 'OpenSans-Medium',
  mainThemeFontFamilyBold: 'OpenSans-Bold',
  udyamAppTertiaryColor: '#FFFFFF',
  themeFontSizeVerySmallHeader: 8,
  themeFontSizeSmall: 9,
  themeFontSizeCardMiniLabel: 10,
  themeFontSizeExtraSmall: 10,
  themeFontSizeDoubleExtraSmall: 10,
  themeFontSizeSmallHeader: 12,
  themeFontSizeMediumHeader: 16,
  themeFontSizeLabel: 14,
  themeFontSizeBigLabel: 15,
  themeFontSizeButton: 16,
  themeFontSizeModalLabel: 18,
  themeFontSizeHeader: 20,
  themeFontSizeLargeHeader: 23,
  themeFontSizeBigHeader: 24,
  themeFontSizeMenuText: 12
};

// to be used only for edge cases in small screens with ui issues
export const udyamitaThemeSm = {
  mainThemeFontFamily: 'OpenSans-Regular',
  mainThemeFontFamilySemiBold: 'OpenSans-Medium',
  mainThemeFontFamilyMedium: 'OpenSans-Regular',
  mainThemeFontFamilyBold: 'OpenSans-Medium',
  themeFontSizeVerySmallHeader: 6,
  themeFontSizeSmall: 8,
  themeFontSizeCardMiniLabel: 8,
  themeFontSizeExtraSmall: 9,
  themeFontSizeDoubleExtraSmall: 9,
  themeFontSizeSmallHeader: 10,
  themeFontSizeMediumHeader: 11,
  themeFontSizeLabel: 12,
  themeFontSizeBigLabel: 12,
  themeFontSizeButton: 12,
  themeFontSizeModalLabel: 14,
  themeFontSizeHeader: 16,
  themeFontSizeLargeHeader: 20,
  themeFontSizeBigHeader: 20,
  themeFontSizeMenuText: 10
};

export const udyamitaThemeLg = {
  mainThemeFontFamily: 'OpenSans-Regular',
  mainThemeFontFamilySemiBold: 'OpenSans-SemiBold',
  mainThemeFontFamilyMedium: 'OpenSans-Medium',
  mainThemeFontFamilyBold: 'OpenSans-Bold',
  themeFontSizeVerySmallHeader: 8,
  themeFontSizeSmall: 9,
  themeFontSizeCardMiniLabel: 10,
  themeFontSizeExtraSmall: 11,
  themeFontSizeDoubleExtraSmall: 11,
  themeFontSizeSmallHeader: 12,
  themeFontSizeMediumHeader: 13,
  themeFontSizeLabel: 14,
  themeFontSizeBigLabel: 15,
  themeFontSizeButton: 16,
  themeFontSizeModalLabel: 18,
  themeFontSizeHeader: 20,
  themeFontSizeLargeHeader: 23,
  themeFontSizeBigHeader: 24,
  themeFontSizeMenuText: 12
};

export const themeSizeWrappedEn = [
  udyamitaTheme,
  udyamitaThemeSm,
  udyamitaThemeLg,
];
